### PR TITLE
PMD in GitHub Actions

### LINKED ISSUE #21: PMD in GitHub Actions.
We should also add this to our GitHub Actions.

_Originally posted by @amuradyan in https://github.com/amuradyan/SuperHotWinXRoyal777/issues/19#issuecomment-1032563572_

### PR DESCRIPTION
**Pull request by RishiKumarRay**
#21

### CODE REVIEW

**Comment by amuradyan** [comment]
@RishiKumarRay Can I ask you to update the distribution on line 27 to `temurin`, while you're at this? I never noticed it but now I checked and it [is advised](https://github.com/actions/setup-java#supported-distributions) to move.

**Comment by RishiKumarRay** [comment]
@amuradyan yeah i have updated this too, thanks

**Review by amuradyan — APPROVED** [review]
This works. Thanks a lot!

**Comment by RishiKumarRay** [comment]
@amuradyan thanks please do review the artifact too that is generated containing report of pmd action. :)

**Comment by Chalyan** [comment]
I linked issue #21 to this PR. Thus it is now closed.

**Pull request merged**
