### PR TITLE
[Doc] Readme draft

### PR DESCRIPTION
**Pull request by amuradyan**
Any ideas?

### CODE REVIEW

**Comment by oshn** [comment]
Idea: :sparkling_heart: 
Implementation: 
image

Apparently GitHub doesn't support CSS in markdown.

###### Alternative Solution

download(2)

**Comment by amuradyan** [comment]
@oshn Idea: 💖

I'd love to have more colors and a gradient though. I'm trying to get the colored letters now.

**Comment by amuradyan** [comment]
Styled text in GitHub markdown became messy, so I'm for the neon one. Can you share the link? I'd like to try the full text / _Welcome to SuperHotWinXRoyal777_ /.

**Comment by amuradyan** [comment]
Oh, and for those who haven't seen what I saw, here you go.

image

**Comment by oshn** [comment]
Check [Animated neon text maker](https://engfto.com/index/animated_neon_text_maker/0-27)

**Comment by amuradyan** [comment]
@Karlengevorgyan91  Are you sure this PR was ready for merging?

**Comment by Karlengevorgyan91** [comment]
@amuradyan No, It was my fault. I will revert the PR

**Pull request merged**
